### ISSUE TITLE
Tools, more blocks and ideas?

### ISSUE THREAD

**Issue by UnintelligentIdiot** [DriHut/ReFramed#3] opened 2024-03-08 18:59 UTC
How about adding the tools screwdriver, hammer, wrench and the blueprint? And adding the half stair, the single cube and the slopes.
~ideas~
~the single cube can be merged with the wrench to create the other blocks
~the slabs to be able to merge as a single block and when broken to drop the double slab block

**Comment by DriHut** [comment] 2024-03-08 23:07
Hi, there are things I did not thought about and will likely add which are the blueprint and hammer I don't know yet about the screwdriver. Concerning the blueprint I'm gonna have to make things be more coherent when it comes to multiple theme placement so that it can be used properly this shouldn't take long.
As for the shapes the slopes are not planed to be added yet even though I got another request to add them. The half stairs will be in the next version as well as the small cube. Version which should be out this week.
Finally being able to merge the shapes like the slabs, the steps, etc... I am planning to add it soon. 
Also be aware that the next version is going to break some of the current properties used by the block due to some coherence issues...

**Comment by UnintelligentIdiot** [comment] 2024-03-08 23:45
No worries at all about the breaking stuff, the screwdriver is used to rotate the textures of the blocks that have rotation like logs, glazed terracotta and so on.
Also with the breaking texture when connected to the floor is that because it is rendered like a glass block or is that just visual bug? Cuz i like using just the blocks.
By slopes i meant the ones that are cube shaped not a normal slope.
And please add panels like the snow layer. 
Thank you for answering and hope u don't ghost this project 🥰

**Comment by DriHut** [comment] 2024-03-09 12:25
The screwdriver could be nice but sometimes you can get block with other properties than just the rotations which it should handle too and I'm not too much into doing that in the near future.
For the connected texture can you send an example because it could be that I setup a model wrongly or its just due to culling which is meant to happen in that case.
For the slopes can you add an example of what you're thinking about ?
I'll also add the panels this week if I can.

**Comment by UnintelligentIdiot** [comment] 2024-03-09 12:32
I will provide every information with pictures tonight as im not at home right now.

**Comment by UnintelligentIdiot** [comment] 2024-03-09 20:43
Sorry i wanted to be faster but it took me a while, also my English isn't the best so please if u can't understand something just tell me.
1~  This is what i meant by connected textures I think this is because of the rendering block status(don't know much about coding but still i know something)
2 ~ 3 ~ Theis are the slopes i meant 
-yellow - Framed Double Slope Panel
-purple- Framed Flat Double Slope Panel Corner
-orange-Framed Double Slope
-green-Framed Double Corner
They don't have to be slopes tho, they can just have each 3 sides of each texture which i think it would be better, but for the corner i guess it would be like the bottom and a side and to be rotatable i guess? 
4 ~  In the original there is kind of the functionality of the single cube.
Add the fence, fence gate, walls and panes(as in glass pane)

![2024-03-09_21 05 55_edited](https://github.com/DriHut/ReFramed/assets/87205739/eb1dc72e-0380-460d-a59f-1fc613729d4a)
![2024-03-09_21 16 29](https://github.com/DriHut/ReFramed/assets/87205739/afbf65da-5566-4d9a-b113-b5afad396ed1)
![2024-03-09_21 17 42](https://github.com/DriHut/ReFramed/assets/87205739/e1ab1fdd-8ac0-4006-989c-b33f1be84d6c)
![2024-03-09_21 19 18](https://github.com/DriHut/ReFramed/assets/87205739/64c6d16a-6045-48a2-be7e-44d788f825af)

**Comment by DriHut** [comment] 2024-03-10 13:48
Hi,
for the first point I can't seem to reproduce the issue... Maybe I fixed it in the newer version I have  locally or maybe you have the game running with another mod that breaks the way I compute the culling? if you had other mods please mention them ^^ Otherwise I'll hope next version fixes it or ill look into it at that point.
For the slopes you are mentioning I don't think ill be adding those soon but since people seems to like slopes a lot I will try adding them at a later stage.
As for the last point I don't think I'll be adding this at all it look like it would be quite the heavy block in terms of computations knowing the current ones are already quite heavy plus probably quite annoying to do the logic of it ^^, .

**Comment by UnintelligentIdiot** [comment] 2024-03-10 16:15
I just figure it that it goes from all of the sides
![2024-03-10_17 09 06](https://github.com/DriHut/ReFramed/assets/87205739/b5479d5e-1dfc-4a17-8c40-ecff207009f4)
This are all the mods i use
[modpack.zip](https://github.com/DriHut/ReFramed/files/14550932/modpack.zip)

**Comment by DriHut** [comment] 2024-03-11 11:28
Ok so its most likely due to another mod incompatibility. Since the list is quite long I won't be looking into that right now as I am currently quite busy but I'll keep this in mind.

**Comment by UnintelligentIdiot** [comment] 2024-03-11 12:03
I figured it out was the "more culling"

**Comment by DriHut** [comment] 2024-03-11 12:04
oh well that's nice to know then if the fix is easy i will implement in in the next version ^^

**Comment by UnintelligentIdiot** [comment] 2024-03-11 12:35
I figured a lot more bugs or wired interactions. 
With Axiom
https://github.com/DriHut/ReFramed/assets/87205739/7abb74e4-8b56-49df-805d-9e07def88ee2
And Cocricot although its new mod for 1.20.4 but still that just those 3 blocks are like that

https://github.com/DriHut/ReFramed/assets/87205739/b3c8954c-3266-4a86-b4f8-f58bdac32faa

**Comment by DriHut** [comment] 2024-03-11 12:41
Yeah for axiom I won't be able to do much except making sure it at least renders the default appearance because the render is based on the block entity which is probably why the models breaks when moving it. For Cocricot I can check but it should be an easy fix.

**Closed as completed** 2024-03-20 15:02 UTC

**Comment by DriHut** [comment] 2024-06-12 12:44
I actually figured out a way to get axiom to correctly render the frames with camos in most cases. If you want to do some testing I'd be down so that next version would be stable on release.
